### ISSUE TITLE
Test IKVM fallback support on non-Windows machines

### ISSUE THREAD

**Issue by sharwell** [tunnelvisionlabs/antlr4cs#130]
Release 4.5-alpha003 included support for using IKVM (bundled) instead of a JRE for generating grammars. This support was tested on Windows machines, but still needs to be tested on non-Windows machines using Mono.

**Comment by sushihangover** [comment]
#### Environment:
* OS-X 10.11.2
* Xamarin Studio Version 5.10.2 (build 49)
* Mono JIT compiler version 4.2.2 (explicit/7b87787 Thu Dec 17 14:29:49 EST 2015

#### IKVM Error:
**Exception in thread "main" cli.System.NotImplementedException: The method or operation is not implemented.**

No `*.cs` files generated in `obj/Debug`

#### Only one file in the test project:
```
  <ItemGroup>
    <Antlr4 Include="EBNF.g4">
      <Generator>MSBuild:Compile</Generator>
      <CustomToolNamespace>RailRoadSharp.Parser</CustomToolNamespace>
    </Antlr4>
  </ItemGroup>
```

#### xbuild EBNF.Parser.csproj (full output)
```
Unknown build error: Executing command: "/Users/sushi/code/sushi/RailRoadSharp/packages/Antlr4.4.5-alpha003/build/../tools/ikvm.exe" -cp /Users/sushi/code/sushi/RailRoadSharp/packages/Antlr4.4.5-alpha003/build/../tools/antlr4-csharp-4.5-SNAPSHOT-complete.jar org.antlr.v4.CSharpTool -o obj/Debug/ -no-listener -no-visitor -package RailRoadSharp.Parser /Users/sushi/code/sushi/RailRoadSharp/EBNF.Parser/EBNF.g4
:  warning AC1000: Unknown build error: Exception in thread "main" cli.System.NotImplementedException: The method or operation is not implemented.
		Previous error was converted to a warning as the task was called with ContinueOnError=true.
:  warning AC1000: Unknown build error: 	at cli.System.Reflection.MemberInfo.get_Module(Unknown Source)
		Previous error was converted to a warning as the task was called with ContinueOnError=true.
:  warning AC1000: Unknown build error: 	at cli.System.Reflection.Emit.FieldBuilder.get_Module(Unknown Source)
		Previous error was converted to a warning as the task was called with ContinueOnError=true.
:  warning AC1000: Unknown build error: 	at IKVM.Internal.FieldWrapper.ResolveField(Unknown Source)
		Previous error was converted to a warning as the task was called with ContinueOnError=true.
:  warning AC1000: Unknown build error: 	at IKVM.NativeCode.sun.reflect.ReflectionFactory+FieldAccessorImplBase+FieldAccessor`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].lazySet(Unknown Source)
		Previous error was converted to a warning as the task was called with ContinueOnError=true.
:  warning AC1000: Unknown build error: 	at IKVM.NativeCode.sun.reflect.ReflectionFactory+FieldAccessorImplBase+FieldAccessor`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].lazySet(Unknown Source)
		Previous error was converted to a warning as the task was called with ContinueOnError=true.
:  warning AC1000: Unknown build error: 	at IKVM.NativeCode.sun.reflect.ReflectionFactory+FieldAccessorImplBase+ObjectField.set(Unknown Source)
		Previous error was converted to a warning as the task was called with ContinueOnError=true.
:  warning AC1000: Unknown build error: 	at java.lang.reflect.Field.set(Field.java)
		Previous error was converted to a warning as the task was called with ContinueOnError=true.
:  warning AC1000: Unknown build error: 	at org.antlr.v4.Tool.handleArgs(Tool.java)
		Previous error was converted to a warning as the task was called with ContinueOnError=true.
	Task "Antlr4ClassGenerationTask" execution -- FAILED
```

#### Using `java -jar` with the same cmd line options

Using the jar included with the Antlr4.4.5-alpha003 nuget works fine.

```
 java -jar /Users/sushi/code/sushi/RailRoadSharp/packages/Antlr4.4.5-alpha003/build/../tools/antlr4-csharp-4.5-SNAPSHOT-complete.jar -Dlanguage=CSharp_v4_5 -o obj/Debug/ -no-listener -no-visitor -package RailRoadSharp.Parser /Users/sushi/code/sushi/RailRoadSharp/EBNF.Parser/EBNF.g4
```
```
├── obj
│   └── Debug
│       ├── EBNF.tokens
│       ├── EBNFLexer.cs
│       ├── EBNFLexer.tokens
│       └── EBNFParser.cs
```
#### Running ikvm manually using the same cmd line options:

```
mono /Users/sushi/code/sushi/RailRoadSharp/packages/Antlr4.4.5-alpha003/build/../tools/ikvm.exe -cp /Users/sushi/code/sushi/RailRoadSharp/packages/Antlr4.4.5-alpha003/build/../tools/antlr4-csharp-4.5-SNAPSHOT-complete.jar org.antlr.v4.CSharpTool -o obj/Debug/ -no-listener -no-visitor -package RailRoadSharp.Parser /Users/sushi/code/sushi/RailRoadSharp/EBNF.Parser/EBNF.g4
```
```
Exception in thread "main" cli.System.NotImplementedException: The method or operation is not implemented.
	at cli.System.Reflection.MemberInfo.get_Module(Unknown Source)
	at cli.System.Reflection.Emit.FieldBuilder.get_Module(Unknown Source)
	at IKVM.Internal.FieldWrapper.ResolveField(Unknown Source)
	at IKVM.NativeCode.sun.reflect.ReflectionFactory+FieldAccessorImplBase+FieldAccessor`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].lazySet(Unknown Source)
	at IKVM.NativeCode.sun.reflect.ReflectionFactory+FieldAccessorImplBase+FieldAccessor`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].lazySet(Unknown Source)
	at IKVM.NativeCode.sun.reflect.ReflectionFactory+FieldAccessorImplBase+ObjectField.set(Unknown Source)
	at java.lang.reflect.Field.set(Field.java)
	at org.antlr.v4.Tool.handleArgs(Tool.java)
```

**Maybe provide a fall back to `java -jar` via an \<Antlr4/\> property (\<ikvm\>false\</ikvm\>)?** Or just do an $OS `UNIX` vs. `WINDOW_NT` check... Would love to actually get this working within Xamarin Studio for a current project...

**Comment by sharwell** [comment]
@sushihangover We already have a fallback to call a different version of `java` (by setting the `JavaExecutable` property in your project file). The problem here is how do you generate code when no java installation is available at all?

**Comment by sushihangover** [comment]
Ahh.... Must have missed the `JavaExecutable` property... I'll re-read the setup docs to find it so I can test the XS/MD IDE integration. 

*Personally* I do not have a problem having Java as a requirement as I have a large number of apps that already require it, but I know it is an issue for some. It would be a nice feature to have it all self-contained with Nuget install for the x-plat support. I do use IKVM in several custom tools to provide a `native` .Net environment, I'll try to take a look to see what feature is throwing the `System.NotImplementedException`.
